services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=crypto_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # ✅ Auto-run SQL script

  airflow_webserver:
    # build: ./airflow  # ✅ Use the custom Dockerfile
    image: apache/airflow:latest
    container_name: airflow_webserver
    restart: always
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:user@postgres_db:5432/crypto_db
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    command: >
      bash -c "
      airflow db upgrade &&
      airflow users create -r Admin -u admin -p admin -e admin@example.com -f Admin -l User &&
      airflow webserver"
    volumes:
      - ./scripts:/scripts
      - ./airflow/dags:/opt/airflow/dags
  airflow_scheduler:
    image: apache/airflow:latest
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - postgres_db
      - airflow_webserver
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:user@postgres_db:5432/crypto_db
    volumes:
      - ./scripts:/scripts
      - ./airflow/dags:/opt/airflow/dags
    command: ["airflow", "scheduler"]

volumes:
  postgres_data: