services:
  source_postgres:
    image: postgres:17
    ports:
      - "5433:5432"
    networks:
      - etl_network
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=source_db
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  destination_postgres:
    image: postgres:17
    ports:
      - "5434:5432"
    networks:
      - etl_network
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=destination_db

  elt_script:
    build:
      context: ./elt_script
      dockerfile: Dockerfile
    command: ["python","elt_script.py"]
    networks:
      - etl_network
    depends_on:
      - source_postgres
      - destination_postgres
    volumes:
      - ./backup:/backup

networks:
  etl_network:
    driver: bridge